server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: zy-system-admin-serve
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    gateway:
      discovery:
        enable: true
        locator:
          enable: true
          lower-case-service-id: true

feign:
  sentinel:
    enabled: true
mybatis-plus:
  enabled: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      auto-fill-enabled: true
      logic-delete-enabled: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-enums-package: cn.com.zy.*.*.enum
  mapper-locations: classpath:cn/com/zy/*/mapper/xml/*Mapper.xml
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      pattern: base
zy:
  avatar-disk-prefix-path: /Users/zy/Downloads
  jwt:
    exclude-path-patterns: /admin/auth/captcha,/admin/auth/login
    gateway-secret: zy.com.cn
    service-secret: zy.com.cn
    minutes: 30
  init-micro-service-security: false

