spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: umisoft.cn
    database: 0
    datasource:
      druid:
        url: jdbc:mysql://127.0.0.1:3306/spring-cloud-platform?useUnicode=true&useSSL=false&characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
    sentinel:
      enabled: true
      transport:
        port: 8846
        dashboard: 127.0.0.1:8847
jetcache:
  remote:
    default:
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}/${spring.redis.database}